---
- hosts: tag_Name_Backend2:tag_Name_Backend2
  user: ubuntu
  become: yes
  tasks:

  - name: Stop running container
    shell: >
      sudo docker stop $(sudo docker ps -a -q)

  - name: Update docker images
    shell: >
      sudo docker pull crocodility/simple-api:main

  - name: Starting docker container
    shell: >
      sudo docker run -d -p 9007:9007 crocodility/simple-api:main